### ISSUE TITLE
When dragging a sprite up or down, the window does not scroll with it

### ISSUE THREAD

**Issue by KnightMiner** [Majr-/SpriteEdit#1]
On most programs with drag and drop support, dragging an item to the top or bottom of the screen causes the screen to scroll so you can place higher or lower than the original screen.

This does not seem to be the case for the sprite editor, which means in order to move something to another section, I have to keep placing it in a section, then scrolling so I can move it further.

**Comment by Majr25** [comment]
Unless you don't have a scroll wheel or touch pad, you can scroll while dragging, which I find far easier to use than auto scroll, which is often either too fast or too slow, and becomes a nuisance when trying to place things near the edge of the screen. Is this method not usable for you?

**Comment by KnightMiner** [comment]
It works fine on my desktop with the scroll wheel. On my laptop, it seems that the touchpad scrolling is disabled when dragging (must be some new Windows 8 "feature"), but apparently I can still use the touch screen scrolling while dragging with the trackpad....

So its not really too much of a problem, just something I expected to happen which can be worked around.
